language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt

  - pip install coveralls

  - pip install pytest-cov

script:
  - python -m pytest --cov
  - coverage run --source=app -m pytest && coverage report

after_success:
  - coveralls