en_errors = {
    0: "okey",
    101: "meet up id has not been set",
    102: "meet up id should be of type string",
    103: "meetup users has not been provided",
    201: "user id is missing",
    202: "user id should be of type integer",
    203: "id of the question has not been set",
    204: "id should be of type integer",
    205: "body of the message has not been set",
    206: "body of the message should be of type string",
    207: "vote is missing in the question",
    208: "vote should be of type integer",
    209: "down vote has not been set",
    210: "down vote should be of type string",
    211: "comment has not been set",
    212: "all comment should be of type list",
    213: "a single comment should be of type dictionary",
    214: "a comment class dunder init method takes in a dictionary as its parameter",
    110: "meetup label should be of type string",
    111: "meetup label has not been set",
    104: "meetup users should be provided using a list of intergers",
    105: "a single user id should be of type int",
    106: "question has not been set",
    107: "a question should be of type dictionary",
    108: "questions has not been set",
    109: "users has not been set",
    112: "a meetup dunder init function takes a dictinary as its parameter",
    501: "bad request format the body should be of type json",
    502: "bad input format use dictionay as input",
    601: "meetup not specified in this question has not been found",
    113: "rsvp not set",
    114: "rsvp should be of type json {}",
    "cor-rsvp": "successfully updated your rsvp",
    "m_rsvp_ue": "user should be of type int",
    "m_rsvp_fe": "rsvp should be yes ,no or maybe",
    401: "user id has not been provided",
    402: "user id should be of type integer",
    403: "first name has not been set",
    404: "first name should be of type string",
    405: "last name has not been set",
    406: "last name should be of type string",
    407: "other-name has not been given",
    408: "other name should be of type string",
    409: "email has not been provided",
    410: "email should be of type string",
    411: "phoneNumber has not been provided",
    412: "phoneNumber should be of type string",
    413: "username has not been provided",
    414: "username should be of type string",
    415: "registered has not been provided",
    416: "registered should be of type string",
    417: "is admin has not been provided",
    418: "is admin should be of type string",
    419: "password has not been provided",
    420: "password should be of type string",
    801: "username already taken",
    802: "email already exists",
    701: "data not of type json as expected",
    506: "data should be of type dictionary",
    507: "username or email has not been provided",
    508: "password has not been provided",
    711: "invalid login information",
    51: "provide a user id",
    52: "user id should be of type integer",
    53: "rsvp should be of type string",
    54: "rsvp has not been set",
    55: "meetup has not been set",
    56: "meetup should be of type integer",
    57: "rsvp data should be of type json",
    58: "rsvp should be a yes no or maybe",
    59: "meetup not found",
    60: "invalid id in url",
    61: "invalid route",
    62: "invalid combinations",
    63: "this route required proper formated json ",
    64: "method not found",
    65: "route not found",
    66: "invalid combinations",
    67: "this route does not use ",
    68: " method",
    69: "there is not meetup with that specic id",
    70: "user list should be provided",
    71: "no question found with that id",
    72: "no question found with that id",
    73: "data inserted correctly",
    74: "invalid route",
    75:"login was successful"

}
