en_errors = {
    0:"okey",
    101: "meet up id has not been set",
    102: "meet up id should be of type string",
    103: "meetup users has not been provided",
    201: "user id should missing",
    202: "user id should be of type integer",
    203: "id of the question has not been set",
    204: "id should be of type integer",
    205: "body of the message has not been set",
    206: "body of the message should be of type string",
    207: "vote is missing in the question",
    208: "vote should be of type integer",
    209: "down vote has not been set",
    210: "down vote should be of type string",
    211: "comment has not been set",
    212: "all comment should be of type list",
    213: "a single comment should be of type dictionary",
    214: "a comment class dunder init method takes in a dictionary as its parameter",
    110: "meetup label should be of type string",
    111: "meetup label has not been set",
    104: "meetup users should be provided using a list of intergers",
    105: "a single user id should be of type int",
    106: "question has not been set",
    107: "a question should be of type dictionary",
    108: "questions has not been set",
    109: "users has not been set",
    112: "a meetup dunder init function takes a dictinary as its parameter",
    501: "bad request format the body should be of type json",
    502: "bad input format use dictionay as input",
    601: "meetup not specified in this question has not been found"

}
